# Generated by Django 3.1.7 on 2022-03-09 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_verifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
