# Generated by Django 3.1.7 on 2022-03-09 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='categories_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('no_of_vacancy', models.PositiveIntegerField()),
                ('offered_salary', models.CharField(max_length=200)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('education_level', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('skills', models.TextField()),
                ('other_specification', models.TextField(blank=True, null=True)),
                ('career_benefits', models.TextField(blank=True, null=True)),
                ('job_address', models.CharField(blank=True, max_length=225, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('job_level', models.CharField(choices=[('Traineeship', 'Traineeship'), ('Internship', 'Internship'), ('Employee', 'Employee')], default='Employee', max_length=50)),
                ('employment_type', models.CharField(choices=[('Full', 'Full'), ('Part', 'Part')], default='Full', max_length=50)),
                ('experienced_required', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
