# Generated by Django 3.1.7 on 2022-04-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
