# Generated by Django 3.1.7 on 2022-04-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0001_initial_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='title',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='github',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='image',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
