"""
Django settings for nepal_police_main project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

from django.conf import settings

from decouple import config
import os
gettext = lambda s: s
DATA_DIR = os.path.dirname(os.path.dirname(__file__))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', False, cast=bool)

RECAPTCHA_SECRET_KEY = config('RECAPTCHA_SECRET_KEY')
RECAPTCHA_SITE_KEY = config('RECAPTCHA_SITE_KEY')

ALLOWED_HOSTS = config("DJANGO_ALLOWED_HOSTS").split(" ")
# Application definition

INSTALLED_APPS = [
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'rest_framework',
]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'dashboard.middleware.ForceDefaultLanguageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.utils.ApphookReloadMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',

    'dashboard.middleware.RestrictUserMiddleware',
    'dashboard.middleware.CmsHomePageMiddleware',
    # 'nepal_police_main.middleware.AdminLocaleURLMiddleware',
    'nepal_police_main.middleware.DashboardLocaleURLMiddleware',
    'nepal_police_main.middleware.BandwidthMiddleware',

]

ROOT_URLCONF = 'nepal_police_main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'builtins': ['user_mgmt.templatetags.user_mgmt_tags'],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'cms.context_processors.cms_settings',
                'django.template.context_processors.i18n',
                'sekizai.context_processors.sekizai',
                'dashboard.context_processors.get_all_menus',
                'dashboard.context_processors.website_logo',
                'dashboard.context_processors.get_notice_types',
                # 'dashboard.context_processors.index'
            ],
        },
    },
]

WSGI_APPLICATION = 'nepal_police_main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('SQL_ENGINE'),
        'NAME': config('SQL_DATABASE'),
        'USER': config('SQL_USER'),
        'PASSWORD': config('SQL_PASSWORD'),
        'HOST': config('SQL_HOST'),
        'PORT': config('SQL_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/


TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# for production
# STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static_cdn')

#for development
STATICFILES_DIRS = (
     os.path.join(BASE_DIR, 'static'),
)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

SITE_ID = 1

LANGUAGE_CODE = 'ne'
LANGUAGES = [
    ('ne', gettext('Nepali')),
    ('en-us', gettext('English')),
]


CMS_PERMISSION = True

CMS_CACHE_DURATIONS = {
    'content':3,
    'menus':180,
    'permissions':180,
}

CMS_TEMPLATES = (
    ('home/homepage.html', 'Index page'),
    ('home/index.html', 'Landing page'),
    ('structure/empty_template.html', 'Empty Template'),
    ('structure/quick-links.html', 'Quick link Template'),
    ('structure/NPA_school_music.html', 'NPA school Template'),
    ('structure/departments.html', 'Department Template'),
    ('structure/Interpol Section.html', 'Interpol Template'),
    ('structure/human right section.html', 'Human Rights section Template'),
    ('contactpage/hospital.html', 'Contact Page'),
    ('safetynsecurity/safetysecuritytips.html', 'safetytips'),
    ('safetynsecurity/policehelpline.html', 'Police Helpline'),
    ('safetynsecurity/emergencynumbers.html', 'Emergency Numbers'),
    # ('home/homepage.html', 'Home Page'),
    ('general_services/general_services.html', 'general_services'),
    # ('fullwidth.html', 'Fullwidth'),
    # ('cms/fullwidth.html', 'Fullwidth'),
    # ('sidebar_left.html', 'Sidebar Left'),
    # ('sidebar_right.html', 'Sidebar Right'),
    ('general_services/general_services.html', 'General Police Service'),
    ('general_services/general_services_detail.html/', 'General Service Detail'),
    ('general_services/publicfacilitylist.html', 'Public Facility List'),
    ('general_services/publicfacilitydetail.html/', 'Public Facility Detail '),
    ('aboutus/police_chief_template.html', 'Police Chief')
)

X_FRAME_OPTIONS = 'SAMEORIGIN'


EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
CONTACT_EMAIL = config('CONTACT_EMAIL')

CELERY_BROKER_URL = config('CELERY_BROKER_URL')

SUMMERNOTE_CONFIG = {
    'height': '300px',
    'width': '100%',
    'summernote': {
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'filerPicture', 'video', 'filerFile']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],
    },
    'css': (
        '/static/filer/css/admin_filer.css',
    ),
    'js': (
        '/static/admin/js/core.js',
        '/static/admin/js/vendor/jquery/jquery.js',
        '/static/admin/js/jquery.init.js',
        '/static/admin/js/admin/RelatedObjectLookups.js',
        '/static/admin/js/actions.js',
        '/static/admin/js/urlify.js',
        '/static/admin/js/prepopulate.js',
        '/static/filer/js/addons/popup_handling.js',
        '/static/filer/js/addons/widget.js',
        '/static/admin/js/related-widget-wrapper.js',
        '/static/js/summernote_filer_image_plugin.js',
        '/static/js/summernote_filer_file_plugin.js',
    ),
}


"""
Configurable session timeout in seconds
to prevent unattended usage of the system
"""
SESSION_COOKIE_AGE = int(config('SESSION_TIMEOUT_SECONDS', 300))

# filer related settings

FILER_ENABLE_PERMISSIONS = True
FILER_ALLOW_REGULAR_USERS_TO_ADD_ROOT_FOLDERS = True
FILER_STORAGES = {
    'public': {
        'main': {
            'ENGINE': 'filer.storage.PublicFileSystemStorage',
            'OPTIONS': {
                'location': MEDIA_ROOT,
                'base_url': MEDIA_URL,
            },
            'UPLOAD_TO': 'filer.utils.generate_filename.randomized',
            'UPLOAD_TO_PREFIX': 'filer_public',
        },
        'thumbnails': {
            'ENGINE': 'filer.storage.PublicFileSystemStorage',
            'OPTIONS': {
                'location': MEDIA_ROOT,
                'base_url': MEDIA_URL,
            },
        },
    },
   
}


# emergency contact APIs
api1 = 'https://apinpima.nepalpolice.gov.np/api/v1/emergency_number_category/get_all'
api2 = 'https://apinpima.nepalpolice.gov.np/api/v1/emergency_number/get_by_categoryid' # remove query params i.e ?id=id

GET_ALL_CATEGORY_API = config('GET_ALL_CATEGORY_API', api1)
GET_BY_CATEGORY_ID_API = config('GET_BY_CATEGORY_ID_API', api2)

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10,
    
    # API throttling
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '2/second'
    }
}

ADMIN_LANGUAGE_CODE = "en-us"